x<-1:100
z<-sample(x,100,replace=TRUE)
mean(z)
var(z)
sd(z)
hist(z,main="Histograma punto 1", ylab="Frecuencia", xlab="Valores")
abline(v=mean(z),col="red", lwd=2, lty=2)
abline(v=mean(z)+sd(z),col="blue", lwd=2, lty=2)
abline(v=mean(z)-sd(z), col="blue", lwd=2, lty=2)
text(50,10,paste("Varianza:", round(var(z),2)), col="black", cex=1.2)
text(50,9,paste("Media:", round(mean(z),2)), col="red", cex=1.2)
text(50,8,paste("Desvio estandar:", round(sd(z),2)), col="blue", cex=1.2)
boxplot(z, main="Diagrama de caja y bigotes", horizontal=TRUE)
stripchart(z,method="jitter",pch=19,add=TRUE,col="blue")
plot(z,main="Diagrama de puntos", xlab="Indice", ylab="Valores")
abline(h=mean(z),col="red",lwd=2,lty=2)